### ISSUE TITLE
Batch export replaces - with _

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/krita-batch-exporter#21]
Following on #20, the add-on currently replaces all sorts of characters from filenames to `_` aggressively. As @Larpon pointed out, you wouldn't expect a layer called e.g. `character-right-arm` to end up as `character_right_arm.png` after export.

I would expect the output to respect the name I wrote, as I wrote it explicitly.

**Comment by razcore-art** [comment]
But then with something like `character - right - arm`, the filename will end up: `character_-_right_-_arm`, we need to think of what rule to follow for converting to `_`

**Comment by NathanLovato** [comment]
As far as replacing characters, dashes are common on the web. On Windows, spaces are common in filenames. So I wouldn't replace these two. As you enter the name explicitly in Krita, I'd say you could replace only symbols that prevent from saving the file; I don't know if there are other common characters you'd use as separators besides ` `, `-`, and `_`.

I wasn't aware of the tool's behavior, now I see how it can look like a bug from the user's perspective. If I input a file name explicitly, I expect it to come out the same.

Then if we're changing this, then I guess we can e.g. expose the JSON config file in the plugin folder to let people pick their delimiter. You already have some config dict in the code anyway, don't you? This would add the flexibility @Larpon suggested at little to no maintenance cost. This way, people could eventually also pick the suffixes' format for filters. E.g. `@0.5x` is common for 50% scale.

**Comment by Larpon** [comment]
According to [this](https://superuser.com/a/358861) - it looks like it's actually only necessary to be aggressive with sanitizing when exporting on windows

**Comment by Larpon** [comment]
> What do you both think?
From what I can think of, it's not a bad idea to expose a user facing config

**Comment by NathanLovato** [comment]
This issue was fixed with 31c3a4b31cfc069ae4e3ae2c20a16821ad6e0928

Regarding exposing the config as JSON, we can open another issue. I'd like to get some more users to play with the add-on to see what should be exposed in there.
