### ISSUE TITLE
Windows install script: Python3 is not a thing bash or WRT can access

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/krita-batch-exporter#35]
Windows store adds a 'python3' program, but it's just an alias that launches the windows store to the python page on microsoft store. Installing the microsoft store version of python and setting it to use python3.exe makes bash give permission denied.

Likely that it's not really in PATH, but is in some windows alias of some sort.

Using the official python installer puts it in the PATH (provided the checkbox has been ticked for it), but python3 is not a thing, just python.exe.

**Comment by NathanLovato** [comment]
Okay, I'll try the `python` command on Windows, and python3 on Unix platforms

**Comment by NathanLovato** [comment]
This should be fixed, could you test and confirm? The python command detection works on Linux at least now

**Comment by Razoric480** [comment]
It works and finds python.exe. However, #36 still happens.

**Comment by NathanLovato** [comment]
Thanks. I've reopened the other issue.
