### ISSUE TITLE
Shell install script on windows: Thinks OS is 'mingw64'

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/krita-batch-exporter#36]
It does not pick up windows as the environment, but mingw64.
```
$ sh install-krita4.2.sh
Your platform, 'mingw64_nt-10.0-18363', is not supported. Exiting the program.
```

I don't have WRT so I can't test what it says there.

~~(Note: to test this I had to edit the script to say `python` instead of `python3`, see #35)~~

**Comment by Razoric480** [comment]
For issue purposes, uname on Git bash gives the string:
`MINGW64_NT-10.0-18363 PaleRazor 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`

**Comment by NathanLovato** [comment]
cut should be able to grab the part before - but the shell might have an issue with the hyphen on windows. I'll process it with grep I guess

**Comment by NathanLovato** [comment]
Ah actually you have Msys, it's just at the end for some reason. I'll try something

**Comment by NathanLovato** [comment]
Okay this should work, hopefully. My previous code had a syntax error. But I changed it to avoid cutting on some weird `uname` output that would fail

**Comment by Razoric480** [comment]
Was a fix pushed or still in progress? I just tried with latest master and it still reports the same error.

**Comment by NathanLovato** [comment]
I tried a fix in the last commit but seems it didn't work. I just pushed another one. In case it wouldn't work, it's line 82:

```sh
platform="$(uname | tr '[:upper:]' '[:lower:]' | cut -d- -f 1)"
```

Could you check that it outputs `mingw64_nt`? There might be something with the syntax of `cut -d- -f1`, I don't know.

**Comment by Razoric480** [comment]
`Successfully installed Krita Batch Exporter in C:\Users\razor\AppData\Roaming/krita/pykrita/krita_batch_exporter`

:)

**Comment by NathanLovato** [comment]
!!!
Thanks for testing this :)
