### ISSUE TITLE
No trimming background?

### ISSUE THREAD

**Issue by ferweer** [GDQuest/krita-batch-exporter#50]
Hi, Sorry for strange English. I not native English speaker.
This addon can add option for no trimming for background or transparent? I want this.
Now all action is always trimming background. So Layer image = Image center. No retention for layer image position. Yes that is kindly for Godot or Blender coatools. But I can't see image anymore on blender CoaTools. sorry stray story. I submit other issue report of afterwards. maybe.

I can tell to this suggested why need. so kind for this result is use bone system animation project. example. Synfig studio, or other animation software of use bone system. Yes I know can using bone system of blender Coatools. but i can't. And I need try another method. 

Or can i change cord to do not trimming of layer transparent? where? I try change python code.

**Comment by ferweer** [comment]
sorry i forgot did not read to How to use it. [t=false] or [t=no] to layer name, that no trimming. ok.
However, I can't use blender coatools now, I want to change default, [t=false] or [t=no] the krita batch exporter defaults. So i means that export for all no trim on no change layer name. except [t=false] or [t=no] tag.
I try change to python code. but where [t=false] or [t=no] set default?

**Comment by NathanLovato** [comment]
All configuration defaults are in Config.py:

```py
CONFIG = {
    "outDir": "export",
    "rootPat": "root",
    "sym": r"[^a-zA-Z0-9_-]",
    "error": {"msg": "ERROR: {}", "timeout": 8000},
    "done": {"msg": "DONE: {}", "timeout": 5000},
    "delimiters": OrderedDict((("assign", "="), ("separator", ","))),  # yapf: disable
    "meta": {"c": [""], "e": ["png"], "m": [0], "p": [""], "t": [""], "s": [100]},
}
```

Change `meta`'s t value to "false":

```py
    "meta": {"c": [""], "e": ["png"], "m": [0], "p": [""], "t": ["false"], "s": [100]},
```

That should solve your issue, if I got it correctly.

**Comment by ferweer** [comment]
thanks. it's work.
