### ISSUE TITLE
Can't see image anymore on blender 2.79 CoaTools.

### ISSUE THREAD

**Issue by ferweer** [GDQuest/krita-batch-exporter#51]
Sorry for strange English, And sorry for early post of no issue report. I do change now this issue report.
Blender 2.79
Coa tools 1.0.4
Krita Batch Exporter 1.1.0
Krita 4.3.0

I can't see Krita export image of blender Coatools. loading JSON, popup dialog this.
`"/USER/blender/addon/import_sorites.py", line 135, in execute
obj = bpy.data.objects[sprite["name]"]
Keyerror: 'bpy_prop_collection[key]: key "image1" not found`

I tried > Copy all export file to different directory. Include export directory or not include export directory. doesn't work. And blender plane object is no have texture. So i can't see image anymore. How that work?

**Comment by NathanLovato** [comment]
I don't think we support the older version of COA for blender 2.79 - in Blender 2.83 it worked no problem.

**Comment by ferweer** [comment]
Yes i use to old version blender. That old and very stability. Blender 2.83 have error and issue more. And have ui probrem. many. I think one case, Scroll bar veeeeery thin. I know that is have issue report.
And i try 2.83 coa tools. Didn't work is install. I can't add addon. I got it. I can't use coa tools. So i stoped to using blender coa tools.  And i did delete and no more install and no more try for coa tools.
But I can use godot and krita and other bone system software. So thanks this product. very helpful. thanks.
So this issue is need to close? This issue no resolve. However other method try is resolve method like? > Not use blender coatools.

**Comment by NathanLovato** [comment]
Yup I'll close for now.
