### ISSUE TITLE
Problem with UPPER/lowercasing of extensions

### ISSUE THREAD

**Issue by Metallicow** [GDQuest/krita-batch-exporter#52]
@GDQuest I'm not sure this is the right place to create an issue, but it appears that this is the starting point for the `export layers`
plugin for Krita 4.4.0.

Anyhow on to the issue details.  Upon export the filenames are being UPPERCASED.
This by default is bad, because some/most linux systems are case sensitive and will cause errors or missing files because it expects the extensions in lowercase. I would suggest this change to the plugin by default.

C:\Users\username\Desktop\krita-x64-4.4.0\share\krita\pykrita\exportlayers\uiexportlayers.py
in `def _exportLayers(self, parentNode, fileFormat, parentDir):`
changed it to be lowercased by default.
`_fileFormat = self.formatsComboBox.currentText().lower()`

In some circumstances besides just basic users(most wouldn't know game development or games, etc...) it may be desirable in rare cases that a person would want the extension to be uppercase. I suggest making a checkbox option in the dialog.

Note that ALLUPPERCASE.png filenames will cause issues with linux flavors also.

Also Note: since we are on the images case subject, I will make a few more improvement suggestions.
[ ] Checkbox option to convert spaces in layer/node names to underscore.
[ ] Checkbox option to completely lowercase filename and extension.

The adding `[png]` to the layer name does make the extension become lowercase, but it also adds `[png]` into the filename that is exported, which at least for me is undesirable.

Anyhow. Thanks in advance. :)

**Comment by NathanLovato** [comment]
The export layers plugin is unrelated to this one. This one is batch exporter

**Comment by Metallicow** [comment]
@NathanLovato Ahhh ha... Ok I see the new one now. The one I was using has a CC0 header. 
It appears to be written by @boudewijnrempt by looking in the krita github history log.
Maybe if I ping boud here he will see it and I won't have to duplicate another issue elsewhere, since it is a smallish fix issue.
Thanks Nathan. Keep up the good work. :)

**Comment by Larpon** [comment]
@Metallicow I suggest that you use [Krita's official bug tracker](https://bugs.kde.org/) - for a higher probability of it getting seen (and eventually fixed) :wink:
