### ISSUE TITLE
Ability to export Group Layer's to single files

### ISSUE THREAD

**Issue by guategeek** [GDQuest/krita-batch-exporter#53]
## Feature request ##

I found your plugin while trying to figure out a workflow similar to the "[Expresso Exporter](https://github.com/fcamarlinghi/expresso)" plugin for Photoshop. I was hoping that as a first step towards that I could possibly export a group layers as separate files, but this functionality doesn't seem to exist in your plugin.

The Expresso Exporter has quite a bit of power, but its main function is to take a folder of layers (a group layer seems to be the Krita alternative) and export that to a new file. So that as a 3D artist you can work manually on say Albedo, Normal, Metalic, Roughness, Emissive ect. all in one file using folders. And then with the click of a button export those to separate maps.

It has fancy features on top, like letting you combine multiple folders into a single output file using different channels, for game engines where say the AO may be combined with the Albedo in the alpha channel, or say combining metallic, roughness and emissive into one map (using R G and B channels for the three separate maps).

Is there any way some of this functionality could be added to your plugin? For example:

- Export Group Layers as a single combined image of all its child layers
- Export to TGA format
- Apply and Invert, Flip X or Y to exported image

**Comment by NathanLovato** [comment]
Exporting group layers to a single image is already supported and working; I use it on every project. It works even with filter layers and everything.

Exporting to TGA isn't supported. I wouldn't personally add support for it. If you'd like to add it, feel free to open a pull request.

And applying effects on export only, that, I wouldn't add it either. At least, I don't see when or how it'd be useful.

When would you need to invert or flip an image only on export? This would mean you'd work on it in Krita without previewing the final result let the exporter modify it? In krita, you can use an invert filter layer and the mirror preview mode to respectively invert your image in a nondestructive way and work on it with the view flipped.

**Comment by guategeek** [comment]
Thanks for the heads up on the group layers thing, just tried it using the "tools/scripts/export layers" and it works great! With that I can get started!

As to the effects on export, some engines use say a normal map with the Y inverted compared to others, in visualizing a normal map it can be easier with the Y different than the engine (lighter green color on top purple color below) so that's a use case. But your tips on the filter layers are a solution to this as well.

Thanks so much for the help, and showing me I don't need your plugin for this use case.

**Comment by NathanLovato** [comment]
Ah, I see what you mean for normals. Yeah, I'd favor a filter in this case. In particular, in Krita, you have a filter to preview normal map lighting and iirc you can preview with channels flipped.

Good luck!
