### ISSUE TITLE
PNG is trimmed even though I'm using "t=false" 

### ISSUE THREAD

**Issue by ilegacy** [GDQuest/krita-batch-exporter#56]
**I'm submitting a...**
[x] Bug report

## Bug report ##

**What is the current behavior?**
After clicking "All Layers" my PNG is trimmed even though I named my layer group "test e=png **t=false**"
![krita_2021-08-30_16-50-02](https://user-images.githubusercontent.com/12360416/131359257-04b14bb1-c3b0-4902-a913-167ce444c93e.png)

**What is the expected behavior?**
The PNG should not be trimmed in any way.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Create a new Krita Image and delete the default (locked) BG-Layer
2. Paint something on "Paint Layer 1"
3. Press Ctrl+G to create a Layer group
4. Name the group "test e=png t=false"
5. Click "All Layers"

**Other information** 

I'm using Krita 5.0.0-beta1

**Comment by razcore-rad** [comment]
The version shipped with Krita is a bit behind and doesn't include the `trim` option. I'm not sure what the workflow is to update the plugin :)

**Comment by ilegacy** [comment]
> 
> 
> The version shipped with Krita is a bit behind and doesn't include the `trim` option. I'm not sure what the workflow is to update the plugin :)

Oh...I thought I'm using bleeding edge krita and just expected that they would use the latest shiny plugins as well. 5.0 beta is the newest one can get, isn't it?

**Comment by razcore-rad** [comment]
Yes, but I don't know what their process of updating the plugin is or even if they even take it into account. You could probably install the latest version from this repo alongside the shipped version.

**Comment by NathanLovato** [comment]
I think we have to update it in Krita, make PRs periodically

**Comment by razcore-rad** [comment]
The latest Krita versions have the updated plugin that includes the fix to this.
