### ISSUE TITLE
Space characters in path

### ISSUE THREAD

**Issue by uszymyszy** [GDQuest/krita-batch-exporter#60]
## Bug report ##
I cannot use spaces in absolute path. Is there any option to use them, like for example "%20"? In some cases like Unity engine it's impossible to remove spaces from main folder due to linked scripts.

**Comment by razcore-rad** [comment]
I'm not sure what @NathanLovato thinks, but I'm inclined to disallow spaces in paths. It's highly likely that it creates an issue one way or another.

I'd rather just document that it doesn't work with spaces.

**Comment by NathanLovato** [comment]
As the user said, if there are folders created by the engine, the add-on should support spaces. with a form like `p="path to output"`. Right now though, I'd need someone to contribute support for this, because we have too much on our plates. We won't have time to work on this anytime soon.

**Comment by uszymyszy** [comment]
From the user perspective it's easy to solve this by putting *kra files inside the Unity game folder and exclude it from the engine by using "~" Then the exported path is for ex. "p=../textures"

But the more elegant solution would be a replacement symbol for space for ex. "#" then:
"p=D:/unity#projects/rat#racer/textures"
and the file will land in:
"D:/unity projects/rat racer/textures"

**Comment by NathanLovato** [comment]
The addon should just support p="some path with spaces" I think.

**Comment by razcore-rad** [comment]
@uszymyszy if you're still interested in this issue, I just updated the plugin to cover the `p="path with spaces"` case, as Nathan suggested. Let us know if it works for you cause I don't have a Windows machine, I can only confirm that it works on Linux so far. Thanks.

**Comment by uszymyszy** [comment]
@razcore-rad I performed a quick test and everything seems to work, the script can also create folders with spaces so it's even better, great work! Now I can separate all .kra files from the game folder and keep them in master folder from where they can be exported to several different projects. Thanks so much for this update!

**Comment by razcore-rad** [comment]
Great, thanks for the confirmation. Closing the issue via 9400819d307b08f7a0945d96c113193f36b422f2
