### ISSUE TITLE
Incorrect export dimensions when t=false and scale<100

### ISSUE THREAD

**Issue by SeanHRN** [GDQuest/krita-batch-exporter#64]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
If I export layers with the names `testB e=png s=30 t=false` and `testA e=png s=30 t=false`, from a canvas that is 1920x1080, the resulting PNGs are of different dimensions and do not retain the proportions of the original image.

**What is the expected behavior?**
The PNGs should have the exact dimensions 576x324 since the contents of each layer are entirely within bounds. Instead, B is 497x40 and A is 540x39.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

As explained above. I'll attach my test document.

[t_test.zip](https://github.com/GDQuest/krita-batch-exporter/files/8192047/t_test.zip)
![testA_@0 3x](https://user-images.githubusercontent.com/99783318/156911605-19513d99-adda-41e7-b674-894cf90684b9.png)
![testB_@0 3x](https://user-images.githubusercontent.com/99783318/156911606-7eba896c-c723-4155-8dc5-92bcdf966cfc.png)

**Comment by razcore-rad** [comment]
Thanks for the heads up. I fixed the issue. Now you'll have to install from this repo instead of using the plugin bundled with Krita because that version will have to catch up to this source.
